version: '3.4'

services:
  librairiepoc2.webservice:
    image: ${DOCKER_REGISTRY-}librairiepoc2webservice
    build:
      context: .
      dockerfile: LibrairiePoc2.WebService/Dockerfile

  db:
    image : docker pull mcr.microsoft.com/mssql/server
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"